---
title: "MIRIS"
subtitle: "Travaux préparatoires"
author: "Philippe MICHEL"
output:
  html_document:
    df_print: paged
    toc: yes
  word_document:
    toc: yes
  html_notebook:
    fig_caption: yes
    theme: spacelab
  pdf_document:
    includes:
      in_header: tete.tex
    keep_tex: yes
    latex_engine: lualatex
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include= FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
#knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
```


```{r info}
rm(list=ls())
library("thesisph")
library("tidyverse")
library("missMDA")
library("epiDisplay")
library("factoextra")
library("lubridate")
library("knitr")
library("finalfit")
library("viridis")
# sessionInfo()
#
```


```{r import}
rm(list = ls())
tt <- read.csv("data/prealable.csv", header= TRUE, dec = ",")
```

```{r tri}
# Tri des patiente aynt eu plus de 2 prélèvements
zz <- tt %>% 
  group_by(nom) %>% 
  summarise(nb = n()) %>% 
  filter(nb > 3)
ttn <- tt %>% 
  filter(tt$nom %in% zz$nom)
```


# Glucides

```{r glucides}
tt %>% 
  ggplot() +
  aes(x = age, y = glucides, color = nature.lait) +
  geom_point() +
  geom_smooth() +
  labs(title = "Glucides",
       x = "Âge (j)",
       y = "mmol/L"
  ) + 
  theme_light() + 
  scale_color_viridis(discrete = TRUE, option = "magma") +
  theme(plot.title = element_text(size=16, face="bold"),
        axis.title.x = element_text(size=12, face="bold"),
        axis.title.y = element_text(size=12, face="bold"),
        axis.text.x = element_text(size=12, face="bold"),
        axis.text.y = element_text(size=12, face="bold"),
        legend.position = "right") 
```


# Protides

```{r Protides}
tt %>% 
  ggplot() +
  aes(x = age, y = protides, color = nature.lait) +
  geom_point() +
  geom_smooth() +
  labs(title = "Protides",
       x = "Âge (j)",
       y = "g/L"
  ) + 
  theme_light() + 
  scale_color_viridis(discrete = TRUE, option = "magma") +
  theme(plot.title = element_text(size=16, face="bold"),
        axis.title.x = element_text(size=12, face="bold"),
        axis.title.y = element_text(size=12, face="bold"),
        axis.text.x = element_text(size=12, face="bold"),
        axis.text.y = element_text(size=12, face="bold"),
        legend.position = "right") 
```

# Lipides

```{r lipides}
tt %>% 
  ggplot() +
  aes(x = age, y = lipides, color = nature.lait) +
  geom_point() +
  geom_smooth() +
  labs(title = "Lipides",
       x = "Âge (j)",
       y = "g/L"
  ) + 
  theme_light() + 
  scale_color_viridis(discrete = TRUE, option = "magma") +
  theme(plot.title = element_text(size=16, face="bold"),
        axis.title.x = element_text(size=12, face="bold"),
        axis.title.y = element_text(size=12, face="bold"),
        axis.text.x = element_text(size=12, face="bold"),
        axis.text.y = element_text(size=12, face="bold"),
        legend.position = "right") 
```